version: '3'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '8899:80'
    volumes:
      - ./:/var/www/html/
    networks:
      - app
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3308:3306'
    networks:
      - app
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '7779:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1
    networks:
      - app
networks:
  app:
volumes:
  db: