version: '3'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '9000:8000'
    volumes:
      - ./src/:/var/www/html/
    networks:
      - app
  db:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3308:3306'
    networks:
      - app
networks:
  app:
volumes:
  db: